#!/usr/bin/env python3
'''Generate installable JavaScript for external reference lookup.'''

from __future__ import annotations

import argparse
from difflib import unified_diff
import importlib.util
import json
from pathlib import Path
import sys


GENERATOR_NAME = "tools/generate-external-references.py"
DEFAULT_OUTPUT = (
    Path("foundry")
    / "generated"
    / "external-references.js"
)


class GenerationError(RuntimeError):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
    )
    parser.add_argument(
        "--check",
        action="store_true",
    )
    return parser.parse_args()


def load_reference_helpers(repo_root: Path):
    path = repo_root / "tools" / "boa-references.py"
    spec = importlib.util.spec_from_file_location(
        "boa_references",
        path,
    )
    if spec is None or spec.loader is None:
        raise GenerationError(
            f"Could not load reference helpers from {path}."
        )

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_json(path: Path) -> object:
    try:
        return json.loads(
            path.read_text(
                encoding="utf-8",
            )
        )
    except FileNotFoundError as error:
        raise GenerationError(
            f"Missing source file: {path}"
        ) from error
    except json.JSONDecodeError as error:
        raise GenerationError(
            f"Invalid JSON in {path}: {error}"
        ) from error


def source_configuration(
    repo_root: Path,
) -> dict[str, object]:
    content_root = (
        repo_root
        / "foundry"
        / "content"
    )
    compatibility = load_json(
        content_root
        / "compatibility.json"
    )
    sources = load_json(
        content_root
        / "references"
        / "external-sources.json"
    )
    references = load_json(
        content_root
        / "references"
        / "external-references.json"
    )

    helpers = load_reference_helpers(
        repo_root
    )
    helpers.validate_reference_sources(
        compatibility,
        sources,
        references,
    )

    return {
        "verifiedEnvironment":
            compatibility["verifiedEnvironment"],
        "sources":
            sources["sources"],
        "references":
            references["references"],
    }


def js_literal(value: object) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )


def rendered_source(
    repo_root: Path,
) -> str:
    configuration = source_configuration(
        repo_root
    )
    return (
        f"/* Generated by {GENERATOR_NAME}. "
        "Do not edit directly. */\n\n"
        "export const BOA_VERIFIED_ENVIRONMENT =\n"
        f"  Object.freeze({js_literal(configuration['verifiedEnvironment'])});\n\n"
        "export const BOA_EXTERNAL_SOURCES =\n"
        f"  Object.freeze({js_literal(configuration['sources'])});\n\n"
        "export const BOA_EXTERNAL_REFERENCES =\n"
        f"  Object.freeze({js_literal(configuration['references'])});\n\n"
        "export function externalReference(key) {\n"
        "  const reference =\n"
        "    BOA_EXTERNAL_REFERENCES[key];\n\n"
        "  if (!reference) {\n"
        "    throw new Error(\n"
        "      `Unknown Bane of Azeroth external reference: ${key}`,\n"
        "    );\n"
        "  }\n\n"
        "  return reference;\n"
        "}\n\n"
        "export function externalReferenceUuid(key) {\n"
        "  return externalReference(key).uuid;\n"
        "}\n"
    )


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    output = (
        args.output
        if args.output.is_absolute()
        else repo_root / args.output
    )
    expected = rendered_source(
        repo_root
    )

    if args.check:
        if not output.is_file():
            print(
                f"Missing generated external-reference module: {output}",
                file=sys.stderr,
            )
            return 1

        actual = output.read_text(
            encoding="utf-8",
        )
        if actual != expected:
            print(
                "Generated external-reference module is out of sync.",
                file=sys.stderr,
            )
            for line in unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=str(output),
                tofile="expected external-reference module",
                lineterm="",
            ):
                print(
                    line,
                    file=sys.stderr,
                )
            return 1

        print(
            "Verified generated external-reference module."
        )
        return 0

    output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )
    output.write_text(
        expected,
        encoding="utf-8",
    )
    print(
        "Generated external-reference module in "
        f"{output.relative_to(repo_root)}."
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as error:
        print(
            f"generate-external-references.py: {error}",
            file=sys.stderr,
        )
        raise SystemExit(1)
